name: Build and Test

on:
  push:
    branches: [feature/develop/task2]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        cd csad2125ki405nikolenkoov21/Client_GUI
        pip install -r requirements.txt

    - name: Build binaries
      run: |
        source venv/bin/activate
        cd csad2125ki405nikolenkoov21/Client_GUI
        pyinstaller --onefile main.py --distpath ../dist
      # Upload binary
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: csad2125ki405nikolenkoov21/dist/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        cd csad2125ki405nikolenkoov21/Client_GUI
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        cd csad2125ki405nikolenkoov21/Client_GUI
        python test_main.py
      # Store test results in artifacts
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: csad2125ki405nikolenkoov21/Client_GUI/test_reports.txt
